#ifndef ECDAA_UTIL_ERRORS_H
#define ECDAA_UTIL_ERRORS_H
#pragma once

#define SUCCESS 0
#define WRITE_TO_FILE_ERROR -1
#define READ_FROM_FILE_ERROR -2
#define KEY_CREATION_ERROR -3
#define DESERIALIZE_KEY_ERROR -5
#define NONCE_OVERFLOW -6
#define CRED_CREATION_ERROR -7
#define SIGNING_ERROR -8
#define PARSE_REVOC_LIST_ERROR -9



#endif
