#!/bin/sh

case "$1" in

        purge|remove)
                ldconfig
        ;;

        upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
                exit 0
        ;;

        *)
                echo "postrm called with unknown argument \`$1'" >&2
                exit 1
        ;;

esac
